#!/bin/execlineb -WP
# SPDX-License-Identifier: EUPL-1.2+
# SPDX-FileCopyrightText: 2020-2022 Alyssa Ross <hi@alyssa.is>
# SPDX-FileCopyrightText: 2025 Demi Marie Obenour <demiobenour@gmail.com>

if { ln -s /proc/self/fd /dev }
if { ln -s /proc/self/fd/0 /dev/stdin }
if { ln -s /proc/self/fd/1 /dev/stdout }
if { ln -s /proc/self/fd/2 /dev/stderr }

if { s6-rc-init -c /etc/s6-rc /run/service }

if { modprobe overlay }
if { mount -a --mkdir }

s6-rc change ok-all
