#!/bin/execlineb -WP
# SPDX-License-Identifier: EUPL-1.2+
# SPDX-FileCopyrightText: 2020-2022, 2024 Alyssa Ross <hi@alyssa.is>

if { s6-rc-init -c /etc/s6-rc /run/service }

if { ln -s /proc/self/fd /dev }
if { ln -s /proc/self/fd/0 /dev/stdin }
if { ln -s /proc/self/fd/1 /dev/stdout }
if { ln -s /proc/self/fd/2 /dev/stderr }

if { mount --make-shared / }
if { mount --make-shared /run }
if { mount -a --mkdir }

s6-rc change ok-all
