# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Generated by scripts/update-nixpkgs.sh.

import (builtins.fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/cab52b36dca5a5a368f05bd03fca0b543b5b9a3e.tar.gz";
  sha256 = "161vhvxj5lmarlagrgcak8yvgwd1llcbfm7g1vqhppy1a7v73y2a";
})
