# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Generated by scripts/update-nixpkgs.sh.

import (builtins.fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/e621b82a26181e7b30f9db2119722b1c00157b47.tar.gz";
  sha256 = "1d20n483s7ls9lz70h0virb03mm8xpid64mm01xmaiqpqimdw7pc";
})
