# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Generated by scripts/update-nixpkgs.sh.

import (builtins.fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/ec33278c3987254b9a209581e5fe8db541a1dc2d.tar.gz";
  sha256 = "1s5xlv4gg66c9wyqz8kjnw0rwqmdg2is4kpa3h52raqci8ci6f7n";
})
