#!/usr/bin/env -S bash --
set -eu
case $0 in
(/*) dir=${0%/*}/..;;
(*/*) dir=./${0%/*}/..;;
(*) dir=..;;
esac
exec git rebase -x "set -eu; \
cd '${dir//\'/\'\\\'\'}'; \
scripts/pre-commit.sh; \
set +e;\
git diff --quiet HEAD -- host/rootfs/gen/file-list.mk img/app/file-list.mk vm/sys/net/file-list.mk;\
case \$? in \
(0) :;;\
(1) git commit --amend -- host/rootfs/gen/file-list.mk img/app/file-list.mk vm/sys/net/file-list.mk;;\
(*) exit \"\$?\";;\
esac" "$@"
