# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Alyssa Ross <hi@alyssa.is>
---
title: Spectrum docs
theme: just-the-docs
plugins:
  - jekyll-asciidoc
exclude:
  - '*.nix'
  - result*
asciidoctor:
  attributes:
    showtitle: '@'
    source-highlighter: rouge
